version: '3.9'
services:
  api:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 4000:4000
    working_dir: /app
    networks:
      - iviewnet
    volumes:
      - ./:/app
    env_file:
      - ./.env
  mysql:
    image: mysql:8.0
    networks:
      - iviewnet
    volumes:
      - i-view-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=i_view_core

volumes:
  i-view-data:

networks:
  iviewnet: {}